name: "Generate 4 billion IPs"

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run IP generation script
      run: node generate4BillionIPs.js
